<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wt_cart_product"
 *
 * Auto generated by Extension Builder 2014-10-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Shopping Cart - Products',
	'description' => 'Sample Product Table for Shopping Cart',
	'category' => 'plugin',
	'author' => 'Daniel Lorenz',
	'author_email' => 'wtcartproduct@extco.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);